-- Create cars table
CREATE TABLE cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    year INTEGER NOT NULL,
    license_plate TEXT,
    vin TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes
CREATE INDEX idx_cars_user_id ON cars(user_id);

-- Add RLS policies
ALTER TABLE cars ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own cars"
    ON cars FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own cars"
    ON cars FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own cars"
    ON cars FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own cars"
    ON cars FOR DELETE
    USING (auth.uid() = user_id);
